services:
  tvheadend:
    build: .
    image: ghcr.io/servercontainers/tvheadend
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev/dvb/adapter0:/dev/dvb/adapter0"
      - "/dev/dvb/adapter1:/dev/dvb/adapter1"
      - "/dev/dvb/adapter2:/dev/dvb/adapter2"
    volumes:
      - ./tvheadend/hts:/root/.hts
      - ./tvheadend/recordings:/root/recordings
      - ./tvheadend/timeshift:/root/timeshift
    ports:
      - 9981:9981
      - 9982:9982
