services:
  tvheadend:
    build: .
    image: ghcr.io/servercontainers/tvheadend
    restart: always
    privileged: true
    devices:
      - "/dev/dvb/adapter0:/dev/dvb/adapter0"
      - "/dev/dvb/adapter1:/dev/dvb/adapter1"
      - "/dev/dvb/adapter2:/dev/dvb/adapter2"
    volumes:
      - ./tvheadend/hts:/usr/share/tvheadend/.hts
      - ./tvheadend/recordings:/usr/share/tvheadend/recordings
      - ./tvheadend/timeshift:/usr/share/tvheadend/timeshift
    ports:
      - 9981:9981
      - 9982:9982
    networks:
      - tvheadend

networks:
  tvheadend:
    driver: bridge
